# Generated by Django 4.2.2 on 2023-07-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_project_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='age',
            field=models.IntegerField(default=21, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
