# Generated by Django 4.2.2 on 2023-07-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_resume_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='al5ha.ductor@gmail.com', max_length=128, verbose_name='Почта'),
            preserve_default=False,
        ),
    ]
